### ISSUE TITLE
Error in Batch Docker

### ISSUE THREAD

**Issue by mwhenderson** [colpal/actions-batch-docker#17]
Looks like we are seeing another error but the actions completed. The images didn't upload to artifact tho.

```
node:1783) UnhandledPromiseRejectionWarning: TypeError: p.map is not a function
    at /home/runner/work/_actions/colpal/actions-batch-docker/v1.3.1/dist/main.js:1:8667
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

_Originally posted by @mwhenderson in https://github.com/colpal/devops-support/issues/465#issuecomment-1298867503_

**Comment by nafarlee** [comment]
Your invocation of `actions-changed-files` is using the `v2` tag, but trying to use the API as if it was still the `v1` tag: https://github.com/colpal/hth-airflow-containers/actions/runs/3370365882/jobs/5591183198#step:13:1. In the v1 releases, `outputs.json` would give a list of files as a JSON array, but now in the `v2` releases it gives a map as a JSON object that has separate properties for `all`, `modified`, `added`, and `deleted`. In other words, you are providing `actions-batch-docker` an object when it expects an array.

Still, the particular error message it gives isn't very helpful, and the fact that it doesn't error the workflow is even less helpful. As much as I think this action shouldn't be used anymore, I have released a new `1.4.0` version that includes:
- an explicit error message if a JSON object is provided
- a correctly failing exit code if unforeseen errors are encountered
- general dependency version bumps
- some revised documentation

The upgrade won't "magically" solve your issue (as the issue was related to incorrect assumptions), but it will make it more clear when this error occurs. You will still need to use the GitHub expression syntax to parse the JSON and then index one of the properties to be provided to `actions-batch-docker`. I still strongly recommend upgrading to the `actions-batch-docker@v1`rolling tag.

**Comment by mwhenderson** [comment]
@nafarlee Keep seeing this sequence template error. I turned on Debug mode but not sure what it is referring too.

https://github.com/colpal/hth-airflow-containers/actions/runs/3388174383/jobs/5629834922

**Comment by mwhenderson** [comment]
Nvm figured it out. need to do toJSON around the whole thing.

`changed-files: '${{ toJSON(fromJSON(steps.changed.outputs.json).all) }}'`

**Comment by nafarlee** [comment]
Ah, that is my mistake too. I will fix the documentation example

**Comment by nafarlee** [comment]
Can this be closed @mwhenderson?
